recipes:
    global:
        - applications::create_var_chef_cache
        - applications::google-chrome
        - applications::firefox
        - applications::java
    mac_os_x:
        - drivers::xerox550
        - osxdefaults::add_note_to_loginscreen
        - osxdefaults::disable_auto-correct
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::disable_resume_system-wide
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop
attributes:
    drivers:
        xerox: 172.18.19.67
    osxdefaults:
        loginmessage: Property of YAKA SARL - zwambo@yaka.fr
